version: '3.8'

services:
    # Frontend
    web:
        image: prayagsingh/web:rn_v1.3
        environment:
            DISABLE_HTTPS: 1
            DISABLE_POLLS: 1
            DEPLOYMENTINFO_SHARD: shard1
            DEPLOYMENTINFO_ENVIRONMENT:
            DEPLOYMENTINFO_ENVIRONMENT_TYPE: #"testing"
            DEPLOYMENTINFO_REGION: Region1
            DEPLOYMENTINFO_USERREGION: Region1
            DISABLE_DEEP_LINKING: "true"
            DISABLE_GRANT_MODERATOR: "true"
            DISABLE_KICKOUT: "true"
            DISABLE_RTX: "false"
            DYNAMIC_BRANDING_URL:
            ENABLE_AUTH: 1
            ENABLE_BREAKOUT_ROOMS: 0
            ENABLE_GUESTS:
            ENABLE_RECORDING: 0
            ENABLE_FILE_RECORDING_SERVICE: "false"
            ENABLE_CALENDAR: "true"
            ENABLE_TRANSCRIPTIONS:
            ENABLE_NO_AUDIO_DETECTION: "true"
            ENABLE_P2P: "true"
            ENABLE_PREJOIN_PAGE: "true"
            ENABLE_XMPP_WEBSOCKET: 1
            ENABLE_COLIBRI_WEBSOCKET: 1
            ENABLE_SUBDOMAINS: "true"
            ENABLE_SIMULCAST: "true"
            ENABLE_REMB: "true"
            ENABLE_TCC: "true"
            ETHERPAD_URL_BASE:
            HIDE_PREMEETING_BUTTONS: invite
            INVITE_SERVICE_URL:
            JICOFO_AUTH_USER: focus
            JIBRI_BREWERY_MUC: jibribrewery
            JIBRI_PENDING_TIMEOUT: 90
            JIBRI_XMPP_USER: jibri
            JIBRI_XMPP_PASSWORD: XXX
            JIBRI_RECORDER_USER: recorder
            JIBRI_RECORDER_PASSWORD: XXX
            NGINX_RESOLVER:
            PUBLIC_URL: https://public_url
            P2P_USE_STUN_TURN:
            P2P_PREFERRED_CODEC: VP9
            RESOLUTION: 720 # default 720
            RESOLUTION_MIN: 360 # default 180
            RESOLUTION_WIDTH:  # default 1280
            RESOLUTION_WIDTH_MIN: # default 320
            START_AUDIO_ONLY:
            START_AUDIO_MUTED:  # default 10
            START_BITRATE:
            START_VIDEO_MUTED:  # default 10
            TESTING_CAP_SCREENSHARE_BITRATE: ""
            TESTING_OCTO_PROBABILITY: 1
            TOOLBAR_BUTTONS: camera,chat,fullscreen,hangup,microphone,mute-everyone,mute-video-everyone,participants-pane,profile,select-background,settings,tileview,toggle-camera,videoquality
            TZ: Asia/Kolkata
            XMPP_DOMAIN: vs.meet.jitsi
            XMPP_AUTH_DOMAIN: auth.vs.meet.jitsi
            XMPP_BOSH_URL_BASE: http://xmpp.vs.meet.jitsi:5280
            XMPP_GUEST_DOMAIN: guest.vs.meet.jitsi
            XMPP_MUC_DOMAIN: muc.vs.meet.jitsi
            XMPP_RECORDER_DOMAIN: recorder.vs.meet.jitsi
            XMPP_SERVER: xmpp.vs.meet.jitsi
            ENABLE_VIDEOQUALITY: 1
            VIDEOQUALITY_PREFERRED_CODEC: VP9
            VIDEOQUALITY_ENFORCE_PREFERRED_CODEC:
            VIDEOQUALITY_BITRATE_VP8_LOW:
            VIDEOQUALITY_BITRATE_VP8_STANDARD:
            VIDEOQUALITY_BITRATE_VP8_HIGH:
            VIDEOQUALITY_BITRATE_VP9_LOW:
            VIDEOQUALITY_BITRATE_VP9_STANDARD:
            VIDEOQUALITY_BITRATE_VP9_HIGH:
        deploy:
          replicas: 1
          update_config:
            failure_action: rollback
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 5

          labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.jitsi-secure.entrypoints=websecure"
            - "traefik.http.routers.jitsi-secure.rule=Host(`public_url`)"
            ## Middleware
            - "traefik.http.routers.jitsi-secure.middlewares=security-headers@file"
            ## LetsEncrypt
            - "traefik.http.routers.jitsi-secure.tls=true"
            - "traefik.http.routers.jitsi-secure.tls.certresolver=letsencrypt"
            - "traefik.http.routers.jitsi-secure.tls.domains[0].main=vs.meet.jitsi"
            - "traefik.http.routers.jitsi-secure.tls.options=myoptions@file"
            ## Service
            - "traefik.http.routers.jitsi-secure.service=jitsi" #here service name is jitsi
            - "traefik.http.services.jitsi.loadbalancer.server.port=80"
            - "traefik.http.services.jitsi.loadbalancer.passhostheader=true"

        volumes:
            - ${CONFIG}/web:/config
        ports:
            - target: 80
        networks:
          proxy:
          jitsi:
            aliases:
              - vs.meet.jitsi
# Custom network so all services can communicate using a FQDN
networks:
  proxy:
    external: true
    name: proxy
  jitsi:
    external: true
    name: jitsi