version: '3.8'

services:
    # XMPP server
    prosody:
        image: prayagsingh/prosody:rn_v1 #unstv1 #wsv25 #24 #23 #20 #18
        hostname: xmpp.vs.meet.jitsi
        deploy:
          replicas: 1
          update_config:
            failure_action: rollback
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 5
        environment:
            AUTH_TYPE: jwt #internal
            DISABLE_POLLS: 1
            ENABLE_AUTH: 1
            ENABLE_AV_MODERATION:
            ENABLE_BREAKOUT_ROOMS: 0
            ENABLE_GUESTS:
            ENABLE_LOBBY:
            ENABLE_XMPP_WEBSOCKET: 1
            #ENABLE_WEBSOCKETS: "true"
            ENABLE_SUBDOMAINS: "true"
            XMPP_CROSS_DOMAIN: "true"
            ENABLE_HTTP_REDIRECT:

            GLOBAL_CONFIG:
            GLOBAL_MODULES:
            LDAP_AUTH_METHOD:
            LDAP_URL:
            LDAP_TLS_CACERT_FILE:
            LDAP_TLS_CACERT_DIR:
            LDAP_BINDPW:
            LDAP_FILTER:
            LDAP_TLS_CHECK_PEER:
            LDAP_START_TLS:
            LDAP_VERSION:
            JICOFO_COMPONENT_SECRET: XXX
            JICOFO_AUTH_USER: focus
            JICOFO_AUTH_PASSWORD: XXX
            JVB_AUTH_USER: jvb
            JVB_AUTH_PASSWORD: XXX
            PUBLIC_URL: https://vs.meet.jitsi
            TURN_CREDENTIALS:
            TURN_HOST:
            TURNS_HOST:
            TURN_PORT:
            TURNS_PORT:
            XMPP_DOMAIN: vs.meet.jitsi
            XMPP_AUTH_DOMAIN: auth.vs.meet.jitsi
            XMPP_BOSH_URL_BASE: http://xmpp.vs.meet.jitsi:5280
            XMPP_GUEST_DOMAIN: guest.vs.meet.jitsi
            XMPP_MUC_DOMAIN: muc.vs.meet.jitsi
            XMPP_INTERNAL_MUC_DOMAIN: internal-muc.vs.meet.jitsi
            XMPP_RECORDER_DOMAIN: recorder.vs.meet.jitsi
            XMPP_MODULES:
            XMPP_MUC_MODULES:
            XMPP_INTERNAL_MUC_MODULES:
            TZ: Asia/Kolkata
            JIGASI_XMPP_USER: jigasi
            JIGASI_XMPP_PASSWORD: XXX
            JIBRI_BREWERY_MUC: jibribrewery
            JIBRI_PENDING_TIMEOUT: 90
            JIBRI_XMPP_USER: jibri
            JIBRI_XMPP_PASSWORD: XXX
            JIBRI_RECORDER_USER: recorder
            JIBRI_RECORDER_PASSWORD: XXX
            JWT_APP_ID: E1B4098799
            JWT_APP_SECRET: XXX
            JWT_ACCEPTED_ISSUERS: my_web_client,my_app_client
            JWT_ALLOW_EMPTY: 0
            JWT_AUTH_TYPE: token
            JWT_TOKEN_AUTH_MODULE: token_verification,token_affiliation
            JWT_ACCEPTED_AUDIENCES: myserver1,myserver2
            JWT_ASAP_KEYSERVER:
            LOG_LEVEL: #debug

        volumes:
            - ${CONFIG}/prosody:/config
            - ${CONFIG}/prosody:/etc/prosody
              #- ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom

        ports:
            - target: 5222
              published: 5222
              #mode: host
            - target: 5347
              published: 5347
              #mode: host
            - target: 5280
              published: 5280
              #mode: host

        networks:
          jitsi:
             aliases:
               - vs.meet.jitsi
               - xmpp.vs.meet.jitsi
               - auth.vs.meet.jitsi
               - guest.vs.meet.jitsi
               - muc.vs.meet.jitsi
               - internal-muc.vs.meet.jitsi
               - focus.vs.meet.jitsi
# Custom network so all services can communicate using a FQDN
networks:
  proxy:
    external: true
    name: proxy
  jitsi:
    external: true
    name: jitsi