export const JVB_SERVER ="vs.reachout.network"
export const JVB_JWT_APP_SECRET="21D40CD42CCA9BE6B8932855781FC840"
export const JVB_JWT_AUD="myserver1"
export const JVB_JWT_ISS="my_web_client"
export const JVB_JWT_APP_ID="E1B40"
export const JITSI_SERVER_DOMAIN="https://vs.reachout.network"
export const RTMP_URL="rtmp://rtmp.livepeer.com/live/d167-mv0l-7mos-a5ia"
